/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toserba;

import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Toserba.Setting.namauser;
import static Toserba.Setting.txt_namauser;
import static Toserba.dataBarang.model;
import static Toserba.dataKaryawan.model;

/**
 *
 * @author ACER
 */
public class Pembelian extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan
     */
    DefaultTableModel modelpb;
    static String selectedBarangID;
    static String namauser;
    public int sub_total;
    public int total;
    public int lainlain;
    ArrayList<String> idlist = new ArrayList<String>();

    public Pembelian() {
        initComponents();
        txt_namauser.setText(namauser);
        if(Login.getLevel().equals("karyawan")){
        btn_master.setEnabled(false);
        } 
        tampil_combo();
        txt_lainlain.setText(String.valueOf(0));
        txt_subtotal.setText(String.valueOf(0));
        txt_total.setText(String.valueOf(0));
        tampilkanbarang();
        tampilkanpembelian();

    }

    public void tampilkanpembelian() {

        String[] judul = {"ID", "Nama Barang", "Harga", "Jumlah"};
        modelpb = new DefaultTableModel(judul, 0);
        tb_pembelian.setModel(modelpb);

    }

    public void tampilkanbarang(){
        DefaultTableModel model;
//        String[] judul = {"ID", "Nama Barang", "Harga"};
        String[] judul = {"ID","Nama Barang", "Harga","Stok"};
        model = new DefaultTableModel(judul, 0);
        tb_barang.setModel(model);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_barang ");
            while (rs.next()) {
//                String data[] = {rs.getString(2), rs.getString(5),rs.getString(3)};
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(5), rs.getString(3)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        master = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        history = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        Profil = new javax.swing.JLabel();
        txt_namauser = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_penjualan = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_lainlain = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        cmb_supplier = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_barang = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pembelian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        btn_history4 = new javax.swing.JButton();
        btn_setting4 = new javax.swing.JButton();
        btn_master4 = new javax.swing.JButton();
        btn_transaksi4 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btn_hapus1 = new javax.swing.JLabel();
        btn_tambah1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        master.setText("Master");
        master.setMaximumSize(new java.awt.Dimension(70, 23));
        master.setMinimumSize(new java.awt.Dimension(70, 23));
        master.setPreferredSize(new java.awt.Dimension(70, 23));
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        transaksi.setText("Transaksi");
        transaksi.setIconTextGap(1);
        transaksi.setMargin(new java.awt.Insets(2, 1, 2, 1));
        transaksi.setMaximumSize(new java.awt.Dimension(70, 23));
        transaksi.setMinimumSize(new java.awt.Dimension(70, 23));
        transaksi.setPreferredSize(new java.awt.Dimension(70, 23));
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        history.setText("History");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        setting.setText("Setting");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1035, 581));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/profil kecil.png"))); // NOI18N
        getContentPane().add(Profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 40));

        txt_namauser.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        txt_namauser.setForeground(new java.awt.Color(255, 255, 255));
        txt_namauser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_namauser.setText("USERNAME");
        getContentPane().add(txt_namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 300, -1));

        txt_cari.setBackground(new java.awt.Color(87, 101, 116));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari.setForeground(new java.awt.Color(255, 255, 255));
        txt_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cari.setText("   Search");
        txt_cari.setBorder(null);
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 180, 30));

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 120, 20));

        jLabel5.setText("Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 100, 20));

        btn_penjualan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/sale38.png"))); // NOI18N
        btn_penjualan.setText("Sell");
        btn_penjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_penjualan.setMaximumSize(new java.awt.Dimension(56, 52));
        btn_penjualan.setMinimumSize(new java.awt.Dimension(56, 52));
        btn_penjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseExited(evt);
            }
        });
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 50, 70));

        btn_pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/puchase38.png"))); // NOI18N
        btn_pembelian.setText("Purchase");
        btn_pembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 60, 70));

        jLabel7.setText("etc");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 100, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 200, 10));

        txt_lainlain.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_lainlain.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_lainlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lainlainActionPerformed(evt);
            }
        });
        txt_lainlain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lainlainKeyReleased(evt);
            }
        });
        getContentPane().add(txt_lainlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 120, 20));

        txt_subtotal.setEditable(false);
        txt_subtotal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 120, 20));

        btn_bayar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/pay60.png"))); // NOI18N
        btn_bayar.setText("PAY");
        btn_bayar.setBorder(null);
        btn_bayar.setContentAreaFilled(false);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 140, 60));

        cmb_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 150, -1));

        tb_barang = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tb_barang.setBackground(new java.awt.Color(87, 101, 116));
        tb_barang.setForeground(new java.awt.Color(255, 255, 255));
        tb_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_barang.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane3.setViewportView(tb_barang);
        if (tb_barang.getColumnModel().getColumnCount() > 0) {
            tb_barang.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 230, 240));

        tb_pembelian.setBackground(new java.awt.Color(87, 101, 116));
        tb_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        tb_pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name of goods", "Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_pembelian.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tb_pembelian);
        if (tb_pembelian.getColumnModel().getColumnCount() > 0) {
            tb_pembelian.getColumnModel().getColumn(1).setPreferredWidth(5);
            tb_pembelian.getColumnModel().getColumn(2).setPreferredWidth(10);
            tb_pembelian.getColumnModel().getColumn(3).setPreferredWidth(15);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 520, 310));

        jLabel3.setText("Supplier");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 50, -1));

        jLabel4.setText("Subtotal ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, 20));

        jLabel6.setText("Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 370, 50, 20));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 150, 20));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 800, -1));

        btn_history4.setBackground(new java.awt.Color(153, 153, 153));
        btn_history4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_history4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/history32.png"))); // NOI18N
        btn_history4.setText("   History");
        btn_history4.setFocusable(false);
        btn_history4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_history4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_history4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_history4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        btn_setting4.setBackground(new java.awt.Color(153, 153, 153));
        btn_setting4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_setting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/setting32.png"))); // NOI18N
        btn_setting4.setText("   Setting");
        btn_setting4.setFocusable(false);
        btn_setting4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_setting4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setting4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setting4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        btn_master4.setBackground(new java.awt.Color(153, 153, 153));
        btn_master4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_master4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/master32.png"))); // NOI18N
        btn_master4.setText("   Master");
        btn_master4.setMargin(new java.awt.Insets(2, 14, 2, 45));
        btn_master4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        btn_transaksi4.setBackground(new java.awt.Color(102, 102, 102));
        btn_transaksi4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_transaksi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/transaksi32.png"))); // NOI18N
        btn_transaksi4.setText("   Transaction");
        btn_transaksi4.setFocusable(false);
        btn_transaksi4.setIconTextGap(1);
        btn_transaksi4.setMargin(new java.awt.Insets(3, 14, 3, 15));
        btn_transaksi4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 50));

        jPanel20.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/shops100.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KasirSHP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 30));

        jPanel12.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 560));

        btn_hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/delete45.png"))); // NOI18N
        btn_hapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapus1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 50, 50));

        btn_tambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/plus45.png"))); // NOI18N
        btn_tambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 50, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_lainlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lainlainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lainlainActionPerformed

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_penjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseEntered
        btn_penjualan.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_btn_penjualanMouseEntered

    private void btn_penjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseExited
        btn_penjualan.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_penjualanMouseExited

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        if (txt_cari.getText().equals("Cari Berdasarkan Nama")) {
            txt_cari.setText("");
            txt_cari.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        if (txt_cari.getText().equals("")) {
            txt_cari.setText("Cari Berdasarkan Nama");
            txt_cari.setForeground(new Color(153, 153, 153));
        } else {
            txt_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        String[] judul = {"ID","Nama Produk","Harga"};
        DefaultTableModel model = new DefaultTableModel(judul, 0);
        tb_barang.setModel(model);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_barang WHERE CONCAT (nama_barang) LIKE '%" + txt_cari.getText() + "%'");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(4)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
       int rows = tb_pembelian.getRowCount();
//       String id_karyawan = Login.id_karyawan;
       String query;
       PreparedStatement ps;
       
       try{
          query = "INSERT INTO tb_pembelian VALUES (null,now(),'"+this.total+"','"+cmb_supplier.getSelectedItem()+"')";
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
           try {
               con.setAutoCommit(false);
               ps = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);     
               ps.executeUpdate();
               ResultSet rs = ps.getGeneratedKeys();
                if(rs.next()){
                    for (int i = 0; i < rows; i++) {
                        query = "INSERT INTO tb_detail_pembelian VALUES ('"+rs.getInt(1)+"','"+tb_pembelian.getValueAt(i, 0).toString()+"','"+tb_pembelian.getValueAt(i, 3).toString()+"')";
                        ps = con.prepareStatement(query);
                        ps.execute();
                        query = "UPDATE tb_barang SET kuantitas = kuantitas + "+Integer.parseInt(tb_pembelian.getValueAt(i, 3).toString())+" WHERE id_barang = '"+tb_pembelian.getValueAt(i,0).toString()+"'";
                        ps = con.prepareStatement(query);
                        ps.execute();
                    }   
                }
                con.commit();
                idlist.clear();
                JOptionPane.showMessageDialog(null, "Transaksi Pembelian Berhasil di Input");
                reset();
                
           } catch (Exception e) {
               con.rollback();
               System.out.println(e.getMessage());
           }
        } 
       catch(Exception e){
               System.out.println(e.getMessage());
       }
       
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_lainlainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lainlainKeyReleased
        try{
        Integer.parseInt(txt_lainlain.getText().toString());
        _settotal();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Masukkan nilai dengan benar");
        }
    }//GEN-LAST:event_txt_lainlainKeyReleased

    private void cmb_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_supplierActionPerformed

    private void btn_history4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_history4ActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_history4ActionPerformed

    private void btn_setting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setting4ActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_setting4ActionPerformed

    private void btn_master4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master4ActionPerformed
        // TODO add your handling code here:
        new dataBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_master4ActionPerformed

    private void btn_transaksi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi4ActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi4ActionPerformed

    private void btn_hapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapus1MouseClicked
        int row = tb_pembelian.getSelectedRow();//0
        idlist.remove(row);
        modelpb.removeRow(row);
        _setsubtotal();
        //            for(int i=0; i<idlist.toArray().length; i++){
            //                if(idlist.toArray()[i].toString() == tb_penjualan.getValueAt(row, 0).toString()){
                //                }
            //                [2] = "JUH"[3]= "BR003" [4]="AAA"
            //            }
        //                result = false;
    }//GEN-LAST:event_btn_hapus1MouseClicked

    private void btn_tambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah1MouseClicked
        // TODO add your handling code here:
        try{
        Integer.parseInt(txt_jumlah.getText());
        
            int row = tb_barang.getSelectedRow();
            boolean result=idlist.contains(tb_barang.getValueAt(row,0).toString());
            if(result==false){
                idlist.add(tb_barang.getValueAt(row,0).toString());
                String data[] = {tb_barang.getValueAt(row, 0).toString(), tb_barang.getValueAt(row, 1).toString(), tb_barang.getValueAt(row, 2).toString(), txt_jumlah.getText()};
                modelpb.addRow(data);
            } else {
                JOptionPane.showMessageDialog(this, "Data barang sudah terinput");
            }
            _setsubtotal();
        }
        
        catch(Exception e){
                JOptionPane.showMessageDialog(this, "Masukkan jumlah dengan benar");
        }
    }//GEN-LAST:event_btn_tambah1MouseClicked

    private void _setsubtotal() {
        int row = tb_pembelian.getRowCount();
        int subtotal = 0;
        for (int i = 0; i < row; i++) {
            int harga_barang = Integer.parseInt(tb_pembelian.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(tb_pembelian.getValueAt(i, 3).toString());
            subtotal = subtotal + (harga_barang * jumlah);
        }
        this.sub_total = subtotal;
        txt_subtotal.setText(String.valueOf(this.sub_total));
        _settotal();
    }
    private void _settotal(){
        this.total = this.sub_total + Integer.parseInt(txt_lainlain.getText().toString());
        txt_total.setText(String.valueOf(this.total));
//        try{
//        }
//        catch(Exception e){
//        JOptionPane.showMessageDialog(null, "Masukkan nilai dengan benar");
//        }
    }
    
    public static void tampil_combo(){
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
        PreparedStatement ps = con.prepareStatement("SELECT * FROM tb_supplier");
        ResultSet rs = ps.executeQuery();
        
            while(rs.next()){
                cmb_supplier.addItem(rs.getString("id_supplier"));
            }
        
        rs.last();
        int jumlahdata = rs.getRow();
        rs.first();
        } catch(Exception e){
    
        }
    
    }
    public void reset(){
        this.sub_total = 0;
        this.total = 0;
        txt_subtotal.setText("");
        txt_lainlain.setText(String.valueOf(this.lainlain));
        txt_total.setText("");
        txt_jumlah.setText("");
        modelpb.setRowCount(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Profil;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JLabel btn_hapus1;
    private javax.swing.JButton btn_history4;
    private javax.swing.JButton btn_master4;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_penjualan;
    private javax.swing.JButton btn_setting4;
    private javax.swing.JLabel btn_tambah1;
    private javax.swing.JButton btn_transaksi4;
    private static javax.swing.JComboBox<String> cmb_supplier;
    private javax.swing.JButton history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton master;
    private javax.swing.JButton setting;
    private javax.swing.JTable tb_barang;
    private javax.swing.JTable tb_pembelian;
    private javax.swing.JButton transaksi;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_lainlain;
    public javax.swing.JLabel txt_namauser;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
