 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toserba;

import com.mysql.jdbc.Statement;
import java.awt.Checkbox;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Toserba.Setting.namauser;
import static Toserba.Setting.txt_namauser;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan
     */
    DefaultTableModel modelpj;
    static String selectedBarangID;
    static String namauser;
    public int sub_total;
    public int total;
    public int ongkir;
    public int berat;
    public int jarak;
    boolean result;
    int row;
    ArrayList<String> idlist = new ArrayList<String>();
    
    public Penjualan() {
        initComponents();
        txt_namauser.setText(namauser);
        if(Login.getLevel().equals("karyawan")){
        btn_master.setEnabled(false);
        } 
        txt_jasakirim.setText("0");
        txt_subtotal.setText("0");
        txt_total.setText("0");
        txt_jarak.setText("0");
        txt_berat.setText("0");
        txt_berat.setEnabled(false);
        txt_jarak.setEnabled(false);
        txt_jasakirim.setEnabled(false);
        tampilkanbarang();
        tampilkanpenjualan();
        
    }
        public void generate() {
        String query = "SELECT * FROM tb_penjualan join tb_detail_penjualan right join tb_barang on tb_barang.id_barang=tb_detail_penjualan.id_barang";
        String path = "C:\\Users\\Ariz\\Downloads\\KangToserba\\src\\Report\\report1.jrxml";

        try {
              Connection koneksi = (Connection) Config.configDB();
            java.sql.Statement pstCek = koneksi.createStatement();
            ResultSet res = pstCek.executeQuery(query);
            JasperDesign design = JRXmlLoader.load(path);
            JasperReport jr = JasperCompileManager.compileReport(design);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(res);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);

            JasperViewer.viewReport(jp);
        } catch(Exception e) { e.printStackTrace(); }
    }
    public void tampilkanpenjualan() {

        String[] judul = {"ID", "Nama Barang", "Harga", "Jumlah"};
        modelpj = new DefaultTableModel(judul, 0);
        tb_penjualan.setModel(modelpj);

    }
    public void tampilkanbarang(){
        DefaultTableModel model;
//        String[] judul = {"ID", "Nama Barang", "Harga"};
        String[] judul = {"ID","Nama Barang", "Harga","Stok"};
        model = new DefaultTableModel(judul, 0);
        tb_barang.setModel(model);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_barang ");
            while (rs.next()) {
//                String data[] = {rs.getString(2), rs.getString(5),rs.getString(3)};
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(5), rs.getString(3)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        master = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        history = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        btn_history1 = new javax.swing.JButton();
        btn_setting1 = new javax.swing.JButton();
        btn_master1 = new javax.swing.JButton();
        btn_transaksi1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Profil1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_history2 = new javax.swing.JButton();
        btn_setting2 = new javax.swing.JButton();
        btn_master2 = new javax.swing.JButton();
        btn_transaksi2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Profil2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_history = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        btn_master = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        Profil4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penjualan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_barang = new javax.swing.JTable();
        Profil = new javax.swing.JLabel();
        txt_namauser = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_penjualan = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opt_jasakirim = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        txt_jarak = new javax.swing.JTextField();
        txt_jasakirim = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_history4 = new javax.swing.JButton();
        btn_setting4 = new javax.swing.JButton();
        btn_master4 = new javax.swing.JButton();
        btn_transaksi4 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btn_hapus1 = new javax.swing.JLabel();
        btn_tambah2 = new javax.swing.JLabel();

        master.setText("Master");
        master.setMaximumSize(new java.awt.Dimension(70, 23));
        master.setMinimumSize(new java.awt.Dimension(70, 23));
        master.setPreferredSize(new java.awt.Dimension(70, 23));
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        transaksi.setText("Transaksi");
        transaksi.setIconTextGap(1);
        transaksi.setMargin(new java.awt.Insets(2, 1, 2, 1));
        transaksi.setMaximumSize(new java.awt.Dimension(70, 23));
        transaksi.setMinimumSize(new java.awt.Dimension(70, 23));
        transaksi.setPreferredSize(new java.awt.Dimension(70, 23));
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        history.setText("History");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        setting.setText("Setting");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        btn_history1.setBackground(new java.awt.Color(0, 153, 153));
        btn_history1.setText("History");
        btn_history1.setFocusable(false);
        btn_history1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_history1ActionPerformed(evt);
            }
        });

        btn_setting1.setBackground(new java.awt.Color(0, 153, 153));
        btn_setting1.setText("Setting");
        btn_setting1.setFocusable(false);
        btn_setting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setting1ActionPerformed(evt);
            }
        });

        btn_master1.setBackground(new java.awt.Color(0, 102, 102));
        btn_master1.setText("Master");
        btn_master1.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master1.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master1.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master1ActionPerformed(evt);
            }
        });

        btn_transaksi1.setBackground(new java.awt.Color(0, 153, 153));
        btn_transaksi1.setText("Transaksi");
        btn_transaksi1.setFocusable(false);
        btn_transaksi1.setIconTextGap(1);
        btn_transaksi1.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btn_transaksi1.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi1.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi1.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        Profil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/LogoSHP (3).png"))); // NOI18N
        jPanel2.add(Profil1);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btn_history2.setBackground(new java.awt.Color(0, 153, 153));
        btn_history2.setText("History");
        btn_history2.setFocusable(false);
        btn_history2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_history2ActionPerformed(evt);
            }
        });

        btn_setting2.setBackground(new java.awt.Color(0, 153, 153));
        btn_setting2.setText("Setting");
        btn_setting2.setFocusable(false);
        btn_setting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setting2ActionPerformed(evt);
            }
        });

        btn_master2.setBackground(new java.awt.Color(0, 102, 102));
        btn_master2.setText("Master");
        btn_master2.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master2.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master2.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master2ActionPerformed(evt);
            }
        });

        btn_transaksi2.setBackground(new java.awt.Color(0, 153, 153));
        btn_transaksi2.setText("Transaksi");
        btn_transaksi2.setFocusable(false);
        btn_transaksi2.setIconTextGap(1);
        btn_transaksi2.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btn_transaksi2.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi2.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi2.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        Profil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/LogoSHP (3).png"))); // NOI18N
        jPanel6.add(Profil2);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        btn_history.setBackground(new java.awt.Color(0, 102, 102));
        btn_history.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_history.setForeground(new java.awt.Color(255, 255, 255));
        btn_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/history32.png"))); // NOI18N
        btn_history.setText("   History");
        btn_history.setFocusable(false);
        btn_history.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });

        btn_setting.setBackground(new java.awt.Color(0, 153, 153));
        btn_setting.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/setting32.png"))); // NOI18N
        btn_setting.setText("   Setting");
        btn_setting.setFocusable(false);
        btn_setting.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });

        btn_master.setBackground(new java.awt.Color(0, 153, 153));
        btn_master.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_master.setForeground(new java.awt.Color(255, 255, 255));
        btn_master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/master32.png"))); // NOI18N
        btn_master.setText("   Master");
        btn_master.setMargin(new java.awt.Insets(2, 14, 2, 45));
        btn_master.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masterActionPerformed(evt);
            }
        });

        btn_transaksi.setBackground(new java.awt.Color(0, 153, 153));
        btn_transaksi.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/transaksi32.png"))); // NOI18N
        btn_transaksi.setText("   Transaction");
        btn_transaksi.setFocusable(false);
        btn_transaksi.setIconTextGap(1);
        btn_transaksi.setMargin(new java.awt.Insets(3, 14, 3, 15));
        btn_transaksi.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));

        Profil4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/LogoSHP (3).png"))); // NOI18N
        jPanel16.add(Profil4);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/wa25.png"))); // NOI18N
        jLabel2.setText("085732214214");
        jPanel16.add(jLabel2);

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));

        jPanel18.setBackground(new java.awt.Color(0, 51, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_penjualan.setBackground(new java.awt.Color(87, 101, 116));
        tb_penjualan.setForeground(new java.awt.Color(255, 255, 255));
        tb_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name of goods", "Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_penjualan.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tb_penjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 530, 320));

        tb_barang = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tb_barang.setBackground(new java.awt.Color(87, 101, 116));
        tb_barang.setForeground(new java.awt.Color(255, 255, 255));
        tb_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of goods", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_barang.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane3.setViewportView(tb_barang);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 220, 250));

        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/profil kecil.png"))); // NOI18N
        getContentPane().add(Profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 40));

        txt_namauser.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        txt_namauser.setForeground(new java.awt.Color(255, 255, 255));
        txt_namauser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_namauser.setText("USERNAME");
        getContentPane().add(txt_namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 5, 300, 30));

        txt_cari.setBackground(new java.awt.Color(87, 101, 116));
        txt_cari.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txt_cari.setForeground(new java.awt.Color(255, 255, 255));
        txt_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cari.setText("   Search");
        txt_cari.setBorder(null);
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 200, 30));

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 130, 20));

        jLabel5.setText("Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 30, -1));

        btn_penjualan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/sale38.png"))); // NOI18N
        btn_penjualan.setText("Sell");
        btn_penjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_penjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 50, 70));

        btn_pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/puchase38.png"))); // NOI18N
        btn_pembelian.setText("Purchase");
        btn_pembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseExited(evt);
            }
        });
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 70));

        jLabel7.setText("Delivery");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel6.setText("distance");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jLabel8.setText("Km");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel9.setText("Heavy");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jLabel10.setText("Kg");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jLabel3.setText("Subtotal ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 60, -1));

        opt_jasakirim.setText("Delivery");
        opt_jasakirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_jasakirimActionPerformed(evt);
            }
        });
        getContentPane().add(opt_jasakirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 80, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 180, -1));

        txt_jarak.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_jarak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jarakActionPerformed(evt);
            }
        });
        txt_jarak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jarakKeyReleased(evt);
            }
        });
        getContentPane().add(txt_jarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 70, 20));

        txt_jasakirim.setEditable(false);
        txt_jasakirim.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_jasakirim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jasakirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jasakirimActionPerformed(evt);
            }
        });
        txt_jasakirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jasakirimKeyReleased(evt);
            }
        });
        getContentPane().add(txt_jasakirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 130, 20));

        txt_berat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_berat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        getContentPane().add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 70, 20));

        txt_subtotal.setEditable(false);
        txt_subtotal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 130, 20));

        btn_bayar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/pay60.png"))); // NOI18N
        btn_bayar.setText("PAY");
        btn_bayar.setBorder(null);
        btn_bayar.setContentAreaFilled(false);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 130, -1));

        jLabel11.setText("Amount");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 380, 50, 20));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 160, -1));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/search28.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 30, 50));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 790, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 180, -1));

        btn_history4.setBackground(new java.awt.Color(153, 153, 153));
        btn_history4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_history4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/history32.png"))); // NOI18N
        btn_history4.setText("   History");
        btn_history4.setFocusable(false);
        btn_history4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_history4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_history4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_history4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        btn_setting4.setBackground(new java.awt.Color(153, 153, 153));
        btn_setting4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_setting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/setting32.png"))); // NOI18N
        btn_setting4.setText("   Setting");
        btn_setting4.setFocusable(false);
        btn_setting4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_setting4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setting4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setting4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        btn_master4.setBackground(new java.awt.Color(153, 153, 153));
        btn_master4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_master4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/master32.png"))); // NOI18N
        btn_master4.setText("   Master");
        btn_master4.setMargin(new java.awt.Insets(2, 14, 2, 45));
        btn_master4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        btn_transaksi4.setBackground(new java.awt.Color(102, 102, 102));
        btn_transaksi4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_transaksi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/transaksi32.png"))); // NOI18N
        btn_transaksi4.setText("   Transaction");
        btn_transaksi4.setFocusable(false);
        btn_transaksi4.setIconTextGap(1);
        btn_transaksi4.setMargin(new java.awt.Insets(3, 14, 3, 15));
        btn_transaksi4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 50));

        jPanel20.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/shops100.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOSERBA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 30));

        jPanel12.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 560));

        btn_hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/delete45.png"))); // NOI18N
        btn_hapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapus1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 50, 40));

        btn_tambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/plus45.png"))); // NOI18N
        btn_tambah2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah2MouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 50, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingActionPerformed

    private void txt_jarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jarakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jarakActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_jasakirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jasakirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jasakirimActionPerformed

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        new Pembelian().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        if(txt_cari.getText().equals("Cari Berdasarkan Nama")) {
            txt_cari.setText("");
            txt_cari.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        if(txt_cari.getText().equals("")) {
            txt_cari.setText("Cari Berdasarkan Nama");
            txt_cari.setForeground(new Color(153, 153, 153));
        } else {
            txt_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
//        String [] judul = {"Nama Produk","Harga","Stok"};
        String [] judul = {"ID","Nama Produk","Harga"};
        DefaultTableModel model = new DefaultTableModel(judul,0);
        tb_barang.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_barang WHERE CONCAT (nama_barang) LIKE '%"+txt_cari.getText()+"%'");
            while(rs.next()){
//                String data [] = {rs.getString(2),rs.getString(5),rs.getString(3)};
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(5)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
       int rows = tb_penjualan.getRowCount();
       String idkaryawan = Login.idkaryawan;
       String query;
       PreparedStatement ps;
       
       try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
          query = "INSERT INTO tb_penjualan VALUES (null,now(),'"+this.total+"','"+idkaryawan+"')";
           try {
               con.setAutoCommit(false);
               ps = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);     
               ps.executeUpdate();
               ResultSet rs = ps.getGeneratedKeys();
//               System.out.println("rows : "+rows);
                if(rs.next()){
                    for (int i = 0; i < rows; i++) {
                        query = "INSERT INTO tb_detail_penjualan VALUES ('"+rs.getInt(1)+"','"+tb_penjualan.getValueAt(i, 0).toString()+"','"+tb_penjualan.getValueAt(i, 3).toString()+"')";
                        ps = con.prepareStatement(query);
                        ps.execute();
                        System.out.println(Integer.parseInt(tb_penjualan.getValueAt(i, 3).toString()));
                    }   
                }
               if(opt_jasakirim.isSelected()){
                   query = "INSERT INTO tb_ongkir VALUES (null,'"+rs.getInt(1)+"','"+this.berat+"','"+this.jarak+"','"+this.ongkir+"')";
                    ps = con.prepareStatement(query);
                    ps.execute();
               } 
                String uang = JOptionPane.showInputDialog("Bayar : ");
                if(Integer.valueOf(uang)>=this.total){
                    con.commit();
                    JOptionPane.showMessageDialog(this,"Kembalian : " + (Integer.valueOf(uang)- this.total));
                    idlist.clear();
                    generate();
                    reset();
                    
                } else {
//                result = false;
                JOptionPane.showMessageDialog(null,"Uang yang dibayarkan tidak cukup");
               con.close();
                } 
                   System.out.println(uang);
                
           } catch (Exception e) {
               con.rollback();
               System.out.println(e.getMessage());
           }
       } 
       catch(Exception e){
       }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        try {
            Integer.parseInt(txt_jumlah.getText());
            row = tb_barang.getSelectedRow();
            String idkolom = tb_barang.getValueAt(row, 0).toString(); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos", "root", "");
            String query = "SELECT kuantitas FROM tb_barang WHERE id_barang= '"+idkolom+"'" ;
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if(rs.next()) {
                if (txt_jumlah.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Masukkan jumlah barang");
                } else {
                    if(Integer.valueOf(rs.getString("kuantitas")) >= Integer.valueOf(txt_jumlah.getText())) {
                        result=idlist.contains(tb_barang.getValueAt(row,0).toString());
                         if(result==false){
                            idlist.add(tb_barang.getValueAt(row,0).toString());
                            String data[] = {tb_barang.getValueAt(row, 0).toString(), tb_barang.getValueAt(row, 1).toString(), tb_barang.getValueAt(row, 2).toString(), txt_jumlah.getText()};
                            modelpj.addRow(data);
                            _setsubtotal();
                         } else{
                            JOptionPane.showMessageDialog(null, "Data barang sudah terinput");
                        }
                    } else{   
                            JOptionPane.showMessageDialog(null, "Stok barang kurang");
                    }
                    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah dengan benar");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void txt_jasakirimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jasakirimKeyReleased
//        _setongkir();
    }//GEN-LAST:event_txt_jasakirimKeyReleased

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased

            _setjasakirim();
    }//GEN-LAST:event_txt_beratKeyReleased

    private void txt_jarakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jarakKeyReleased

        // TODO add your handling code here:
        _setjasakirim();
    }//GEN-LAST:event_txt_jarakKeyReleased

    private void btn_pembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseEntered
        btn_pembelian.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_btn_pembelianMouseEntered

    private void btn_pembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseExited
        btn_pembelian.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_pembelianMouseExited

    private void btn_history1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_history1ActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_history1ActionPerformed

    private void btn_setting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setting1ActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_setting1ActionPerformed

    private void btn_master1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_master1ActionPerformed

    private void btn_transaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi1ActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi1ActionPerformed

    private void btn_history2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_history2ActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_history2ActionPerformed

    private void btn_setting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setting2ActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_setting2ActionPerformed

    private void btn_master2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_master2ActionPerformed

    private void btn_transaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi2ActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi2ActionPerformed

    private void opt_jasakirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_jasakirimActionPerformed
        if(opt_jasakirim.isSelected()) {
            txt_berat.setEnabled(true);
            txt_jarak.setEnabled(true);
            txt_jasakirim.setEnabled(true);
        } else {
            this.ongkir = 0;
            this.berat = 0;
            this.jarak = 0;
            txt_jasakirim.setText(String.valueOf(this.ongkir));
            txt_berat.setText(String.valueOf(this.ongkir));
            txt_jarak.setText(String.valueOf(this.ongkir));
            txt_berat.setEnabled(false);
            txt_jarak.setEnabled(false);
            txt_jasakirim.setEnabled(false);
            _settotal();
            //        txt_total_set
            //        txt_total.setText(String.valueOf(this.total-this.ongkir));

        }
    }//GEN-LAST:event_opt_jasakirimActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_historyActionPerformed

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_settingActionPerformed

    private void btn_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_masterActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_history4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_history4ActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_history4ActionPerformed

    private void btn_setting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setting4ActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_setting4ActionPerformed

    private void btn_master4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master4ActionPerformed
        // TODO add your handling code here:
        new dataBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_master4ActionPerformed

    private void btn_transaksi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi4ActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi4ActionPerformed

    private void btn_hapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapus1MouseClicked
        int row = tb_penjualan.getSelectedRow();//0
        idlist.remove(row);
        modelpj.removeRow(row);
        _setsubtotal();
        //            for(int i=0; i<idlist.toArray().length; i++){
            //                if(idlist.toArray()[i].toString() == tb_penjualan.getValueAt(row, 0).toString()){
                //                }
            //                [2] = "JUH"[3]= "BR003" [4]="AAA"
            //            }
        //                result = false;
    }//GEN-LAST:event_btn_hapus1MouseClicked

    private void btn_tambah2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah2MouseClicked
        // TODO add your handling code here:
        try{
            Integer.parseInt(txt_jumlah.getText());

            int row = tb_barang.getSelectedRow();
            boolean result=idlist.contains(tb_barang.getValueAt(row,0).toString());
            if(result==false){
                idlist.add(tb_barang.getValueAt(row,0).toString());
                String data[] = {tb_barang.getValueAt(row, 0).toString(), tb_barang.getValueAt(row, 1).toString(), tb_barang.getValueAt(row, 2).toString(), txt_jumlah.getText()};
                modelpj.addRow(data);
            } else {
                JOptionPane.showMessageDialog(this, "Data barang sudah terinput");
            }
            _setsubtotal();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Masukkan jumlah dengan benar");
        }
    }//GEN-LAST:event_btn_tambah2MouseClicked
    private void _setsubtotal() {
        int row = tb_penjualan.getRowCount();
        int subtotal = 0;
        for (int i = 0; i < row; i++) {
            int harga_barang = Integer.parseInt(tb_penjualan.getValueAt(i, 2).toString()); //22000
            int jumlah = Integer.parseInt(tb_penjualan.getValueAt(i, 3).toString()); //11
            subtotal = subtotal + (harga_barang * jumlah);
          //subtotal = 15000 + (23*11)
          //subtotal = 15000 + 253
          //subtotal = 15253
          //subtotal = 15253 + (22000*11)
          //subtotal = 15253 + 242000
          //subtotal = 257253
        }
        this.sub_total = subtotal;
        txt_subtotal.setText(String.valueOf(this.sub_total));
        _settotal();
    }
    private void _setjasakirim(){
        this.berat = Integer.valueOf(txt_berat.getText());
        this.jarak = Integer.valueOf(txt_jarak.getText());
        this.ongkir = berat * jarak * 3000;
        txt_jasakirim.setText(String.valueOf(this.ongkir));
        _settotal();
     
    }
    
    public void _settotal(){
        this.total = this.sub_total + this.ongkir;
        txt_total.setText(String.valueOf(this.total));
    }
    public void reset(){
        this.sub_total = 0;
        this.total = 0;
        txt_subtotal.setText("0");
        txt_total.setText("0");
        txt_jumlah.setText("0");
        txt_jasakirim.setText("0");
        txt_berat.setText("0");
        txt_jarak.setText("0");
        modelpj.setRowCount(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Profil;
    private javax.swing.JLabel Profil1;
    private javax.swing.JLabel Profil2;
    private javax.swing.JLabel Profil4;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JLabel btn_hapus1;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_history1;
    private javax.swing.JButton btn_history2;
    private javax.swing.JButton btn_history4;
    private javax.swing.JButton btn_master;
    private javax.swing.JButton btn_master1;
    private javax.swing.JButton btn_master2;
    private javax.swing.JButton btn_master4;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_penjualan;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_setting1;
    private javax.swing.JButton btn_setting2;
    private javax.swing.JButton btn_setting4;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel btn_tambah2;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_transaksi1;
    private javax.swing.JButton btn_transaksi2;
    private javax.swing.JButton btn_transaksi4;
    private javax.swing.JButton history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton master;
    private javax.swing.JCheckBox opt_jasakirim;
    private javax.swing.JButton setting;
    private javax.swing.JTable tb_barang;
    private javax.swing.JTable tb_penjualan;
    private javax.swing.JButton transaksi;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_jarak;
    private javax.swing.JTextField txt_jasakirim;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JLabel txt_namauser;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
