/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toserba;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ACER
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    static String namauser; 
    static String id_karyawan;
    public Setting() {
        initComponents();
        if(Login.getLevel().equals("karyawan")){
        btn_master4.setEnabled(false);
        } 
        txt_namauser.setText(namauser);
        txt_nama.setBackground(new java.awt.Color(0,0,0,1));
        txt_jeniskelamin.setBackground(new java.awt.Color(0,0,0,1));
        txt_tanggallahir.setBackground(new java.awt.Color(0,0,0,1));
        txt_nohp.setBackground(new java.awt.Color(0,0,0,1));
        txt_alamat.setBackground(new java.awt.Color(0,0,0,1));
        txt_email.setBackground(new java.awt.Color(0,0,0,1));
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_karyawan WHERE id_karyawan ='"+id_karyawan+"'");
            while(rs.next()){
                txt_nama.setText(rs.getString("nama_karyawan"));
                txt_jeniskelamin.setText(rs.getString("jenis_kelamin"));
                txt_tanggallahir.setText(rs.getString("tgl_lahir"));
                txt_nohp.setText(rs.getString("no_hp"));
                txt_alamat.setText(rs.getString("alamat"));
                txt_email.setText(rs.getString("email"));
            }
        }
        catch (SQLException ex){
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ubahkatasandi = new javax.swing.JButton();
        btn_ubahusername = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_namauser = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_tanggallahir = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_jeniskelamin = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        btn_history4 = new javax.swing.JButton();
        btn_setting4 = new javax.swing.JButton();
        btn_master4 = new javax.swing.JButton();
        btn_transaksi4 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ubahkatasandi.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_ubahkatasandi.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubahkatasandi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Buttons64.png"))); // NOI18N
        btn_ubahkatasandi.setText("Password Edit");
        btn_ubahkatasandi.setBorder(null);
        btn_ubahkatasandi.setContentAreaFilled(false);
        btn_ubahkatasandi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_ubahkatasandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahkatasandiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubahkatasandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 180, 40));

        btn_ubahusername.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_ubahusername.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubahusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Buttons64.png"))); // NOI18N
        btn_ubahusername.setText("Username Edit");
        btn_ubahusername.setBorder(null);
        btn_ubahusername.setContentAreaFilled(false);
        btn_ubahusername.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_ubahusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahusernameMouseClicked(evt);
            }
        });
        btn_ubahusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahusernameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubahusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 180, 50));

        btn_logout.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/logiut31.png"))); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.setBorder(null);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 100, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 101, 116));
        jLabel4.setText("Biodata Karyawan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/profil gede.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(87, 101, 116));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(87, 101, 116));
        jLabel6.setText(":");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(87, 101, 116));
        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 101, 116));
        jLabel8.setText("Tanggal Lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 90, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(87, 101, 116));
        jLabel9.setText("No. Telp");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(87, 101, 116));
        jLabel10.setText("Alamat");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(87, 101, 116));
        jLabel11.setText("Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(87, 101, 116));
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(87, 101, 116));
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 10, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(87, 101, 116));
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 10, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(87, 101, 116));
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(87, 101, 116));
        jLabel16.setText(":");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 10, -1));

        txt_namauser.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        txt_namauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_namauser.setToolTipText("");
        getContentPane().add(txt_namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 260, 40));

        txt_nama.setEditable(false);
        txt_nama.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_nama.setBorder(null);
        txt_nama.setDisabledTextColor(new java.awt.Color(152, 148, 148));
        txt_nama.setDoubleBuffered(true);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 300, 20));

        txt_tanggallahir.setEditable(false);
        txt_tanggallahir.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_tanggallahir.setBorder(null);
        txt_tanggallahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggallahirActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 300, 20));

        txt_nohp.setEditable(false);
        txt_nohp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_nohp.setBorder(null);
        txt_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 300, 20));

        txt_alamat.setEditable(false);
        txt_alamat.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_alamat.setBorder(null);
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 300, 20));

        txt_email.setEditable(false);
        txt_email.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 300, 20));

        txt_jeniskelamin.setEditable(false);
        txt_jeniskelamin.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_jeniskelamin.setBorder(null);
        txt_jeniskelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_jeniskelamin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_jeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jeniskelaminActionPerformed(evt);
            }
        });
        getContentPane().add(txt_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 300, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 200, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 490, 550));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, 10));

        jPanel2.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 300, 540));

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 780, -1));

        btn_history4.setBackground(new java.awt.Color(153, 153, 153));
        btn_history4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_history4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/history32.png"))); // NOI18N
        btn_history4.setText("   History");
        btn_history4.setFocusable(false);
        btn_history4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_history4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_history4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_history4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        btn_setting4.setBackground(new java.awt.Color(102, 102, 102));
        btn_setting4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_setting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/setting32.png"))); // NOI18N
        btn_setting4.setText("   Setting");
        btn_setting4.setFocusable(false);
        btn_setting4.setMargin(new java.awt.Insets(2, 14, 3, 45));
        btn_setting4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setting4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setting4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        btn_master4.setBackground(new java.awt.Color(153, 153, 153));
        btn_master4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_master4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/master32.png"))); // NOI18N
        btn_master4.setText("   Master");
        btn_master4.setMargin(new java.awt.Insets(2, 14, 2, 45));
        btn_master4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_master4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_master4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_master4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        btn_transaksi4.setBackground(new java.awt.Color(153, 153, 153));
        btn_transaksi4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_transaksi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/transaksi32.png"))); // NOI18N
        btn_transaksi4.setText("   Transaction");
        btn_transaksi4.setFocusable(false);
        btn_transaksi4.setIconTextGap(1);
        btn_transaksi4.setMargin(new java.awt.Insets(3, 14, 3, 15));
        btn_transaksi4.setMaximumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setMinimumSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.setPreferredSize(new java.awt.Dimension(70, 23));
        btn_transaksi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 50));

        jPanel20.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/shops100.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TOSERBA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 30));

        jPanel12.setBackground(new java.awt.Color(87, 101, 116));
        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_tanggallahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggallahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggallahirActionPerformed

    private void txt_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_jeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jeniskelaminActionPerformed

    private void btn_ubahusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahusernameMouseClicked
        
    }//GEN-LAST:event_btn_ubahusernameMouseClicked

    private void btn_ubahusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahusernameActionPerformed
        new ubahUsername().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ubahusernameActionPerformed

    private void btn_ubahkatasandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahkatasandiActionPerformed
        new ubahSandi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ubahkatasandiActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_history4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_history4ActionPerformed
        new History().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_history4ActionPerformed

    private void btn_setting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setting4ActionPerformed
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_setting4ActionPerformed

    private void btn_master4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master4ActionPerformed
        // TODO add your handling code here:
        new dataBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_master4ActionPerformed

    private void btn_transaksi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi4ActionPerformed
        new Penjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_history4;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_master4;
    private javax.swing.JButton btn_setting4;
    private javax.swing.JButton btn_transaksi4;
    private javax.swing.JButton btn_ubahkatasandi;
    private javax.swing.JButton btn_ubahusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_jeniskelamin;
    private javax.swing.JTextField txt_nama;
    public static javax.swing.JLabel txt_namauser;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txt_tanggallahir;
    // End of variables declaration//GEN-END:variables
}
