package Toserba;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class tambahSupplier extends javax.swing.JFrame {

    /**
     * Creates new form tambahSupplier
     */
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    String sql;
    public tambahSupplier() {
        initComponents();
//        txt_idsupplier.setText(String.valueOf(1));
        idsupplier();
//        buatnomor();
    }
    public void idsupplier() {
        try {
            con=(Connection)Config.configDB();
            String sql = "SELECT MAX(id_supplier)as max FROM tb_supplier";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                String NoJual = rs.getString("max").substring(2);
                String AN = "" + (Integer.valueOf(NoJual) + 1);
//                String AN = "" + (Integer.parseInt(txt_idsupplier.getText()) + 1);
                String Nol = "";

                if(AN.length()==1)
                    {Nol = "000";
                }else if(AN.length()==2){
                    Nol = "00";
                }else if(AN.length()==3){
                    Nol = "0";
                }else if(AN.length()==4){
                    Nol = "";
                }
                txt_idsupplier.setText("SP" + Nol + AN);//sesuaikan dengan variable namenya
            } else {
                txt_idsupplier.setText("SP0001");//sesuaikan dengan variable namenya
            }
            rs.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_idsupplier = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txt_id.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tambah Supplier ");
        txt_id.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setText("Nama Supplier");
        txt_id.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 124, -1, -1));

        jLabel3.setText("Alamat");
        txt_id.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 168, -1, -1));

        jLabel4.setText("No. Hp");
        txt_id.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 215, -1, -1));
        txt_id.add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 215, 166, -1));
        txt_id.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 165, 166, -1));
        txt_id.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 121, 166, -1));
        txt_id.add(txt_idsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 166, -1));

        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Group 14(1).png"))); // NOI18N
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        txt_id.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 145, 29));

        jLabel6.setText("ID");
        txt_id.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
            try{
//            String nohp=txt_nohp.getText();
//                int nohpcvt = (txt_nohp.getText());
                Long.parseLong(txt_nohp.getText());
//                System.out.println("An integer");
            String idbarang=txt_idsupplier.getText();
            String nama=txt_nama.getText();
            String alamat=txt_alamat.getText();
                PreparedStatement ps = con.prepareStatement("INSERT INTO tb_supplier (id_supplier, nama_supplier, alamat, no_hp) VALUES ('"+idbarang+"', '" + nama + "', '" + alamat + "', '" +txt_nohp.getText()+ "')");
                ps.execute();
                JOptionPane.showMessageDialog(null,"Data supplier berhasil ditambahkan");
                dataSupplier.tampilkanSupplier();
                dispose();
            
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Masukkan nomor HP dengan benar");
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"ID supplier telah terdaftar");
            Logger.getLogger(dataSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_submitActionPerformed
//private void idsupplier()
//    {
        
    
//       try {
//            sql="select * from tb_supplier order by id_supplier desc";
//            con=(Connection)Config.configDB();
//            st=con.createStatement();
//            rs=st.executeQuery(sql);
//            if (rs.next()) {
//                String idsup = rs.getString("id_supplier").substring(1);
//                String AN = "" + (Integer.parseInt(idsup) + 1);
//                String Nol = "";
//
//                if(AN.length()==1)
//                {Nol = "000";}
//                else if(AN.length()==2)
//                {Nol = "00";}
//                else if(AN.length()==3)
//                {Nol = "0";}
//                else if(AN.length()==4)
//                {Nol = "";}
//
//               txt_idsupplier.setText("SP" + Nol + AN);
//            } else {
//               txt_idsupplier.setText("SP001");
//            }
//
//           }catch(Exception e){
//           JOptionPane.showMessageDialog(null, e);
//           }
//     }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JPanel txt_id;
    private javax.swing.JTextField txt_idsupplier;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
