/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toserba;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Toserba.ubahUsername.usernamelama;

/**
 *
 * @author ACER
 */
public class ubahSandi extends javax.swing.JFrame {

    /**
     * Creates new form ubahSandi
     */
    static String sandilama;
    public ubahSandi() {
        initComponents();
        txt_sandibaru.setBackground(new java.awt.Color(0,0,0,1));
        txt_sandilama.setBackground(new java.awt.Color(0,0,0,1));
        txt_ksandibaru.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_sandilama = new javax.swing.JPasswordField();
        txt_sandibaru = new javax.swing.JPasswordField();
        txt_ksandibaru = new javax.swing.JPasswordField();
        btn_konfirmasi = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Back.png"))); // NOI18N
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/profil gede.png"))); // NOI18N
        jPanel1.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 180, 190));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ubah Kata Sandi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 290, 40));

        txt_sandilama.setText("Masukkan Password Lama");
        txt_sandilama.setBorder(null);
        txt_sandilama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sandilamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_sandilamaFocusLost(evt);
            }
        });
        txt_sandilama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sandilamaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sandilama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 280, 20));

        txt_sandibaru.setText("Masukkan Password Baru");
        txt_sandibaru.setBorder(null);
        txt_sandibaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sandibaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_sandibaruFocusLost(evt);
            }
        });
        txt_sandibaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sandibaruActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sandibaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 280, 20));

        txt_ksandibaru.setText("Verifikasi Password Baru");
        txt_ksandibaru.setBorder(null);
        txt_ksandibaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ksandibaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ksandibaruFocusLost(evt);
            }
        });
        jPanel1.add(txt_ksandibaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 280, 20));

        btn_konfirmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Group 4(2)(1).png"))); // NOI18N
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 220, 40));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Tamplate (1).png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sandibaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sandibaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sandibaruActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void txt_sandilamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sandilamaFocusGained
        if(txt_sandilama.getText().equals("Masukkan Password Lama")) {
            txt_sandilama.setText("");
            txt_sandilama.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_sandilamaFocusGained

    private void txt_sandilamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sandilamaFocusLost
        if(txt_sandilama.getText().equals("")) {
            txt_sandilama.setText("Masukkan Password Lama");
            txt_sandilama.setForeground(new Color(153, 153, 153));
        } else {
            txt_sandilama.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_sandilamaFocusLost

    private void txt_sandibaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sandibaruFocusGained
        if(txt_sandibaru.getText().equals("Masukkan Password Baru")) {
            txt_sandibaru.setText("");
            txt_sandibaru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_sandibaruFocusGained

    private void txt_sandibaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sandibaruFocusLost
        if(txt_sandibaru.getText().equals("")) {
            txt_sandibaru.setText("Masukkan Password Baru");
            txt_sandibaru.setForeground(new Color(153, 153, 153));
        } else {
            txt_sandibaru.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_sandibaruFocusLost

    private void txt_ksandibaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ksandibaruFocusGained
        if(txt_ksandibaru.getText().equals("Verifikasi Password Baru")) {
            txt_ksandibaru.setText("");
            txt_ksandibaru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_ksandibaruFocusGained

    private void txt_ksandibaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ksandibaruFocusLost
        if(txt_ksandibaru.getText().equals("")) { 
            txt_ksandibaru.setText("Verifikasi Password Baru");
            txt_ksandibaru.setForeground(new Color(153, 153, 153));
        } else {
            txt_ksandibaru.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_ksandibaruFocusLost

    private void txt_sandilamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sandilamaActionPerformed
        
    }//GEN-LAST:event_txt_sandilamaActionPerformed

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
            PreparedStatement ps = con.prepareStatement("UPDATE tb_akun SET password='"+txt_sandibaru.getText()+"' WHERE username='"+usernamelama+"'");
            if(!txt_sandilama.getText().equals(sandilama)){
                JOptionPane.showMessageDialog(null,"Sandi lama yang dimasukkan tidak cocok");
            } else {
                if(txt_sandibaru.getText().equals(sandilama)){
                    JOptionPane.showMessageDialog(null,"Sandi baru yang dimasukkan harus berbeda dengan sandi lama");
                } else { 
                    if(txt_sandibaru.getText().equals(txt_ksandibaru.getText())) {
                    ps.execute(); 
                    JOptionPane.showMessageDialog(null,"Berhasil Mengubah sandi");
                    dispose();                          
                    new Login().setVisible(true);
                } else { 
                    JOptionPane.showMessageDialog(null,"Masukkan sandi ulang dengan benar");
                }
                    
                }
            }
            }
        catch (SQLException ex){
            Logger.getLogger(ubahSandi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahSandi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel profil;
    private javax.swing.JPasswordField txt_ksandibaru;
    private javax.swing.JPasswordField txt_sandibaru;
    private javax.swing.JPasswordField txt_sandilama;
    // End of variables declaration//GEN-END:variables
}
