package Toserba;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Toserba.History.model;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class ubahUsername extends javax.swing.JFrame {

    /**
     * Creates new form ubahUsernamee
     */
    static String usernamelama;
    public ubahUsername() {
        initComponents();
        txt_usernamebaru.setBackground(new java.awt.Color(0,0,0,1));
        txt_usernamelama.setBackground(new java.awt.Color(0,0,0,1));
//        System.out.println(usernamelama);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_back = new javax.swing.JLabel();
        txt_usernamelama = new javax.swing.JTextField();
        txt_usernamebaru = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_konfirmasi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Back.png"))); // NOI18N
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 42, 47));

        txt_usernamelama.setText("Masukkan Username Lama");
        txt_usernamelama.setToolTipText("");
        txt_usernamelama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_usernamelama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernamelamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernamelamaFocusLost(evt);
            }
        });
        txt_usernamelama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernamelamaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usernamelama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 20));

        txt_usernamebaru.setText("Masukkan Username Baru");
        txt_usernamebaru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_usernamebaru.setCaretColor(new java.awt.Color(153, 153, 153));
        txt_usernamebaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernamebaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernamebaruFocusLost(evt);
            }
        });
        txt_usernamebaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernamebaruActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usernamebaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 230, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/profil gede.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 180, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ubah Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 265, -1));

        btn_konfirmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Group 4(2)(1).png"))); // NOI18N
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 220, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Toserba/icon/Ubah Username(3)(1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernamelamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernamelamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernamelamaActionPerformed

    private void txt_usernamebaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernamebaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernamebaruActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        new Setting().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void txt_usernamelamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernamelamaFocusGained
        if(txt_usernamelama.getText().equals("Masukkan Username Lama")) {
            txt_usernamelama.setText("");
            txt_usernamelama.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_usernamelamaFocusGained

    private void txt_usernamelamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernamelamaFocusLost
        if(txt_usernamelama.getText().equals("")) {
            txt_usernamelama.setText("Masukkan Username Lama");
            txt_usernamelama.setForeground(new Color(153, 153, 153));
        } else {
            txt_usernamelama.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_usernamelamaFocusLost

    private void txt_usernamebaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernamebaruFocusGained
        if(txt_usernamebaru.getText().equals("Masukkan Username Baru")) {
            txt_usernamebaru.setText("");
            txt_usernamebaru.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_usernamebaruFocusGained

    private void txt_usernamebaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernamebaruFocusLost
        if(txt_usernamebaru.getText().equals("")) {
            txt_usernamebaru.setText("Masukkan Username Baru");
            txt_usernamebaru.setForeground(new Color(0, 0, 0));
        } else {
            txt_usernamebaru.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_usernamebaruFocusLost

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sinarharapanpos","root","");
            PreparedStatement ps = con.prepareStatement("UPDATE tb_akun SET username='"+txt_usernamebaru.getText()+"' WHERE username='"+usernamelama+"'");
            if(!txt_usernamelama.getText().equals(usernamelama)){
                JOptionPane.showMessageDialog(null,"Username lama yang dimasukkan tidak cocok dengan username lama");
            } else {
                if(txt_usernamebaru.getText().equals(usernamelama)){
                    JOptionPane.showMessageDialog(null,"Username baru yang dimasukkan harus berbeda dengan username lama");
                } else {
                    ps.execute(); 
                    JOptionPane.showMessageDialog(null,"Berhasil mengganti username");
//                    dispose();
                    this.setVisible(false);
                    new Login().setVisible(true);
                }
            }
            }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Username telah dipakai oleh karyawan lain");
            Logger.getLogger(ubahUsername.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
//                    if(txt_usernamebaru.getText().equals(txt_usernamelama.getText())){
//                        JOptionPane.showMessageDialog(null,"Username baru yang dimasukkan harus berbeda dengan username lama");
//                        } else { ps.execute(); dispose();
//                            new Setting().setVisible(true);}
//            }
        
//            if(txt_usernamelama.getText()== usernamelama && txt_usernamebaru.getText()!= txt_usernamelama.getText()){
//            ps.execute(); 
//            dispose();
//            new Setting().setVisible(true);
//            } else {
//            JOptionPane.showMessageDialog(null,"Cek kembali username lama atau baru");
//            }
            
//                if(txt_usernamelama.getText()==usernamelama){
//                    if(txt_usernamebaru.getText()== usernamelama){
//                    ps.execute();
//                    } else {
//                    JOptionPane.showMessageDialog(null,"Username yang dimasukkan harus berbeda dengan username lama");}        
//                    } else {
//                    JOptionPane.showMessageDialog(null,"Username yang dimasukkan tidak cocok dengan username lama");
//                    }
            
        
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahUsername().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_usernamebaru;
    private javax.swing.JTextField txt_usernamelama;
    // End of variables declaration//GEN-END:variables
}
